networks:
  my-network:
    external: false

services:
  server:
    image: python:latest
    hostname: server
    ports:
      - "8000:8000"
    container_name: server
    restart: unless-stopped
    networks:
      - my-network
    build:
      context: ./
      dockerfile: Dockerfile
    logging:
      options:
        max-size: 50m