networks:
  my-network:
    external: false

services:
  score-service:
    image: python:latest
    hostname: score-service
    ports:
      - "8080:8080"
    container_name: score-service
    restart: unless-stopped
    networks:
      - my-network
    build:
      context: ./
      dockerfile: Dockerfile
    logging:
      options:
        max-size: 50m